
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = '1DARRBOOL 1DARRINT 2DARRBOOL 2DARRINT ASGN BACK BOOL CBOOL CLOSEBR CLOSEIND CLOSEST COMMA CUINT DEC DIV DO ELSE EQ EXTEND1 EXTEND2 FALSE FORW FUNC GETB GETF GETL GETR GT ID IF INC LEFT LT MINUS MUL NL NOT NUM OPENBR OPENIND OPENST OR PLUS PUSHB PUSHF PUSHL PUSHR RET RIGHT SZ1 SZ2 TRUE UINT UNDO WHILEprogram : stmt_liststmt_list : stmt_list statement\n                     | statementstatement : expr\n                     | OPENST statement CLOSESTexpr : expr PLUS term\n                | expr MINUS term\n                | termterm : term MUL factor\n                | term DIV factor\n                | factorfactor : OPENBR expr CLOSEBRfactor : MINUS factorfactor : NUMfactor : ID'
    
_lr_action_items = {'OPENST':([0,2,3,4,5,6,8,10,11,12,18,20,21,22,23,24,25,],[5,5,-3,-4,5,-8,-11,-14,-15,-2,-13,-6,-7,-5,-9,-10,-12,]),'OPENBR':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,20,21,22,23,24,25,],[9,9,-3,-4,9,-8,9,-11,9,-14,-15,-2,9,9,9,9,-13,-6,-7,-5,-9,-10,-12,]),'MINUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,],[7,7,-3,14,7,-8,7,-11,7,-14,-15,-2,7,7,7,7,-13,14,-6,-7,-5,-9,-10,-12,]),'NUM':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,20,21,22,23,24,25,],[10,10,-3,-4,10,-8,10,-11,10,-14,-15,-2,10,10,10,10,-13,-6,-7,-5,-9,-10,-12,]),'ID':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,20,21,22,23,24,25,],[11,11,-3,-4,11,-8,11,-11,11,-14,-15,-2,11,11,11,11,-13,-6,-7,-5,-9,-10,-12,]),'$end':([1,2,3,4,6,8,10,11,12,18,20,21,22,23,24,25,],[0,-1,-3,-4,-8,-11,-14,-15,-2,-13,-6,-7,-5,-9,-10,-12,]),'CLOSEST':([4,6,8,10,11,15,18,20,21,22,23,24,25,],[-4,-8,-11,-14,-15,22,-13,-6,-7,-5,-9,-10,-12,]),'PLUS':([4,6,8,10,11,18,19,20,21,23,24,25,],[13,-8,-11,-14,-15,-13,13,-6,-7,-9,-10,-12,]),'CLOSEBR':([6,8,10,11,18,19,20,21,23,24,25,],[-8,-11,-14,-15,-13,25,-6,-7,-9,-10,-12,]),'MUL':([6,8,10,11,18,20,21,23,24,25,],[16,-11,-14,-15,-13,16,16,-9,-10,-12,]),'DIV':([6,8,10,11,18,20,21,23,24,25,],[17,-11,-14,-15,-13,17,17,-9,-10,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmt_list':([0,],[2,]),'statement':([0,2,5,],[3,12,15,]),'expr':([0,2,5,9,],[4,4,4,19,]),'term':([0,2,5,9,13,14,],[6,6,6,6,20,21,]),'factor':([0,2,5,7,9,13,14,16,17,],[8,8,8,18,8,8,8,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmt_list','program',1,'p_program','parser.py',54),
  ('stmt_list -> stmt_list statement','stmt_list',2,'p_stmt_list','parser.py',59),
  ('stmt_list -> statement','stmt_list',1,'p_stmt_list','parser.py',60),
  ('statement -> expr','statement',1,'p_statement','parser.py',68),
  ('statement -> OPENST statement CLOSEST','statement',3,'p_statement','parser.py',69),
  ('expr -> expr PLUS term','expr',3,'p_expr','parser.py',78),
  ('expr -> expr MINUS term','expr',3,'p_expr','parser.py',79),
  ('expr -> term','expr',1,'p_expr','parser.py',80),
  ('term -> term MUL factor','term',3,'p_term','parser.py',88),
  ('term -> term DIV factor','term',3,'p_term','parser.py',89),
  ('term -> factor','term',1,'p_term','parser.py',90),
  ('factor -> OPENBR expr CLOSEBR','factor',3,'p_factor','parser.py',98),
  ('factor -> MINUS factor','factor',2,'p_factor_un','parser.py',103),
  ('factor -> NUM','factor',1,'p_factor_const','parser.py',108),
  ('factor -> ID','factor',1,'p_factor_id','parser.py',113),
]
